### ISSUE TITLE
Cannot run gh-pages on Windows

### ISSUE THREAD

**Issue by ydogandjiev** [tomchentw/react-google-maps#180]
I am trying to add support for KmlLayers to the react-google-maps module but I am encountering an issue when trying to run the gh-pages project. The following command throws an error:
`npm run start:windows`

It looks like the issue is related to the reacthtmlpack devServer functionality:
```
> gh-pages@1.0.0 start:windows C:\Users\yudogan\react-google-maps\examples\gh-pages
> reacthtmlpack devServer ./Client.webpackConfig.js ../../public './views/**/*.html.js'

C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\rx\dist\rx.js:77
    throw e;
    ^

TypeError: Cannot read property 'port' of undefined
    at AnonymousObservable.__subscribe (C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\reacthtmlpack\lib\core\webpack.js:266:25)
    at AnonymousObservable.tryCatcher (C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\rx\dist\rx.js:63:31)
    at setDisposable (C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\rx\dist\rx.js:5709:44)
    at AnonymousObservable.Rx.AnonymousObservable.AnonymousObservable._subscribe (C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\rx\dist\rx.js:5726:9)
    at AnonymousObservable.Rx.Observable.observableProto.subscribe.observableProto.forEach (C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\rx\dist\rx.js:2024:19)
    at MergeAllObserver.next (C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\rx\dist\rx.js:3772:37)
    at MergeAllObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\rx\dist\rx.js:1752:31)
    at MergeAllObserver.tryCatcher (C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\rx\dist\rx.js:63:31)
    at AutoDetachObserverPrototype.next (C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\rx\dist\rx.js:5747:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (C:\Users\yudogan\react-google-maps\examples\gh-pages\node_modules\rx\dist\rx.js:1752:31)
```

The npm debug log is here:
[npm-debug.txt](https://github.com/tomchentw/reacthtmlpack/files/76020/npm-debug.txt)

**Comment by ydogandjiev** [comment]
I just tried running the gh-pages project on OS X following the exact same setup steps that I used on Windows and it works without issue. The problem described above appears to be Windows-specific.

**Comment by WillemLabu** [comment]
+1

**Comment by tomchentw** [comment]
Guess it might be path resolution issue. I'm refactoring on `reacthtmlpack` recently so won't have time to look into this. Sorry about that :(

**Comment by tomchentw** [comment]
We're going to look into this shortly.

We're also looking for maintainers. Involve in #266 to help strengthen our community!
