### ISSUE TITLE
Deployment reported failure after success.

### ISSUE THREAD

**Issue by timothyarmes** [tomchentw/react-google-maps#232]
I created a new DO server and installed the latest version of this project. The deployment did actually work (I can access my app), however mup reported a failure.

Everything went well until the very last moment:

```
Verifying Deployment: FAILED
	
Error: 
-----------------------------------STDERR-----------------------------------
 run:
npm WARN deprecated 
npm WARN deprecated   npm -g install npm@latest
npm WARN deprecated 
npm WARN deprecated (Depending on how Node.js was installed on your system, you
npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
npm WARN deprecated on Windows, run them from an Administrator prompt.)
npm WARN deprecated 
npm WARN deprecated If you're running the version of npm bundled with
npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
npm WARN deprecated will be bundled with a version of npm@2, which has some small
npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
npm WARN deprecated semver behavior.
npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data

> fibers@1.0.8 install /bundle/bundle/programs/server/node_modules/fibers
> node build.js || nodejs build.js

-----------------------------------STDOUT-----------------------------------

To see more logs type 'mup logs --tail=50'

----------------------------------------------------------------------------
    at /Users/Tim/Development/meteor-up/node_modules/nodemiral/lib/coreTasks.js:39:16
    at /Users/Tim/Development/meteor-up/node_modules/nodemiral/lib/session.js:146:9
    at Channel.<anonymous> (/Users/Tim/Development/meteor-up/node_modules/nodemiral/lib/ssh.js:125:9)
    at emitOne (events.js:90:13)
    at Channel.emit (events.js:182:7)
    at SSH2Stream.<anonymous> (/Users/Tim/Development/meteor-up/node_modules/ssh2/lib/Channel.js:124:14)
    at SSH2Stream.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at SSH2Stream.emit (events.js:179:7)
    at parsePacket (/Users/Tim/Development/meteor-up/node_modules/ssh2-streams/lib/ssh.js:3435:10)
    at SSH2Stream._transform (/Users/Tim/Development/meteor-up/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/Tim/Development/meteor-up/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:301:12)
    at writeOrBuffer (_stream_writable.js:287:5)
```

If I get the logs:

```
macpro:do-newmup Tim$ mup logs --tail=1000
[xx.xx.xx.xxx]npm WARN deprecated This version of npm lacks support for important features,
[xx.xx.xx.xxx]npm WARN deprecated such as scoped packages, offered by the primary npm
[xx.xx.xx.xxx]npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
[xx.xx.xx.xxx]npm WARN deprecated latest stable version. To upgrade to npm@2, run:
[xx.xx.xx.xxx]npm WARN deprecated 
[xx.xx.xx.xxx]npm WARN deprecated   npm -g install npm@latest-2
[xx.xx.xx.xxx]npm WARN deprecated 
[xx.xx.xx.xxx]npm WARN deprecated To upgrade to the latest stable version, run:
[xx.xx.xx.xxx]npm WARN deprecated 
[xx.xx.xx.xxx]npm WARN deprecated   npm -g install npm@latest
[xx.xx.xx.xxx]npm WARN deprecated 
[xx.xx.xx.xxx]npm WARN deprecated (Depending on how Node.js was installed on your system, you
[xx.xx.xx.xxx]npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
[xx.xx.xx.xxx]npm WARN deprecated on Windows, run them from an Administrator prompt.)
[xx.xx.xx.xxx]npm WARN deprecated 
[xx.xx.xx.xxx]npm WARN deprecated If you're running the version of npm bundled with
[xx.xx.xx.xxx]npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
[xx.xx.xx.xxx]npm WARN deprecated will be bundled with a version of npm@2, which has some small
[xx.xx.xx.xxx]npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
[xx.xx.xx.xxx]npm WARN deprecated semver behavior.
[xx.xx.xx.xxx]npm WARN package.json meteor-dev-bundle@0.0.0 No description
[xx.xx.xx.xxx]npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
[xx.xx.xx.xxx]npm WARN package.json meteor-dev-bundle@0.0.0 No README data
[xx.xx.xx.xxx]
[xx.xx.xx.xxx]> fibers@1.0.8 install /bundle/bundle/programs/server/node_modules/fibers
[xx.xx.xx.xxx]> node build.js || nodejs build.js
[xx.xx.xx.xxx]
[xx.xx.xx.xxx]make: Entering directory `/bundle/bundle/programs/server/node_modules/fibers/build'
[xx.xx.xx.xxx]  CXX(target) Release/obj.target/fibers/src/fibers.o
[xx.xx.xx.xxx]  CXX(target) Release/obj.target/fibers/src/coroutine.o
[xx.xx.xx.xxx]  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
[xx.xx.xx.xxx]  SOLINK_MODULE(target) Release/obj.target/fibers.node
[xx.xx.xx.xxx]  SOLINK_MODULE(target) Release/obj.target/fibers.node: Finished
[xx.xx.xx.xxx]  COPY Release/fibers.node
[xx.xx.xx.xxx]make: Leaving directory `/bundle/bundle/programs/server/node_modules/fibers/build'
[xx.xx.xx.xxx]Installed in `/bundle/bundle/programs/server/node_modules/fibers/bin/linux-x64-v8-3.14/fibers.node`
[xx.xx.xx.xxx]ansi-regex@0.2.1 node_modules/ansi-regex
[xx.xx.xx.xxx]ansi-styles@1.1.0 node_modules/ansi-styles
[xx.xx.xx.xxx]escape-string-regexp@1.0.5 node_modules/escape-string-regexp
[xx.xx.xx.xxx]chalk@0.5.1 node_modules/chalk
[xx.xx.xx.xxx]supports-color@0.2.0 node_modules/supports-color
[xx.xx.xx.xxx]has-ansi@0.1.0 node_modules/has-ansi
[xx.xx.xx.xxx]strip-ansi@0.3.0 node_modules/strip-ansi
[xx.xx.xx.xxx]eachline@2.3.3 node_modules/eachline
[xx.xx.xx.xxx]type-of@2.0.1 node_modules/type-of
[xx.xx.xx.xxx]amdefine@1.0.0 node_modules/amdefine
[xx.xx.xx.xxx]asap@2.0.3 node_modules/asap
[xx.xx.xx.xxx]underscore@1.5.2 node_modules/underscore
[xx.xx.xx.xxx]meteor-promise@0.5.1 node_modules/meteor-promise
[xx.xx.xx.xxx]promise@7.0.4 node_modules/promise
[xx.xx.xx.xxx]source-map-support@0.3.2 node_modules/source-map-support
[xx.xx.xx.xxx]semver@4.1.0 node_modules/semver
[xx.xx.xx.xxx]source-map@0.1.32 node_modules/source-map
[xx.xx.xx.xxx]fibers@1.0.8 node_modules/fibers
[xx.xx.xx.xxx]=> Starting meteor app on port:80
[xx.xx.xx.xxx]Kadira: completed instrumenting the app
```

**Comment by timothyarmes** [comment]
Sorry, I posted this to the wrong project!

**Comment by tomchentw** [comment]
No problem!
