### ISSUE TITLE
Can't get cloned application to work on my local machine

### ISSUE THREAD

**Issue by spolisetty** [tomchentw/react-google-maps#314]
Hello All, I'm new to using this react component/library. I tried following the basic instructions on the Readme page, Without Docker installation. 

- npm install - works
- cd examples/gh-pages - works (Obviously!) 
- npm install - works
- npm start - throws the following error (See below)

Then open http://localhost:8080/webpack-dev-server - nothing displays

Do anyone of you see errors like this? I really like this library, and the examples, which I could use. But unfortunately getting it to work locally and then into another project is getting in the way. Please let me know if you think there's a quick fix or a better Getting Started guide, that works without error. 

Thanks!
PS:
```javascript
MacBook-Pro:gh-pages testuser$ npm start

> gh-pages@1.0.0 prestart /Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages
> npm run clean


> gh-pages@1.0.0 clean /Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages
> rimraf ../../public/index.html ../../public/async ../../public/assets


> gh-pages@1.0.0 start /Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages
> cross-env NODE_ENV=development reacthtmlpack devServer $npm_package_config_reacthtmlpack_devServer

webpack built 73c7264f8647a789ca77 in 16476ms
webpack built 46c5753529a80fdba602 in 16928ms
ERRRRRRRRRORRRRRR
ERRRRRRRRRORRRRRR
ERRRRRRRRRORRRRRR
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at dirname (path.js:1324:5)
    at run (/Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages/node_modules/eval-as-module/index.js:37:37)
    at evaluateAsES2015Module (/Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages/node_modules/reacthtmlpack/lib/html/elementProcessor.js:64:46)
    at _callee$ (/Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages/node_modules/reacthtmlpack/lib/html/elementProcessor.js:124:49)
    at tryCatch (/Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages/node_modules/regenerator-runtime/runtime.js:62:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages/node_modules/regenerator-runtime/runtime.js:336:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages/node_modules/regenerator-runtime/runtime.js:95:21)
    at step (/Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages/node_modules/reacthtmlpack/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/testuser/Development/JavaScript/React/react-google-maps/examples/gh-pages/node_modules/reacthtmlpack/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14

**Comment by MychaelZ** [comment]
I'm also getting errors.

**Comment by tomchentw** [comment]
@spolisetty @MychaelZ We did a rewrite for #318 . This should be pretty easy now.

Also,  [6.0.0](https://github.com/tomchentw/react-google-maps/issues/318) is released on npm beta tag now. We also have a new demo page. Feel free to try it:
https://tomchentw.github.io/react-google-maps/
