### ISSUE TITLE
es2015-loose couldn't be found

### ISSUE THREAD

**Issue by dvf** [tomchentw/react-google-maps#526]
I'm pretty new to JS, so forgive me if this is something silly, but I can't seem to build my project after installing this library. Importing: `import { withGoogleMap, GoogleMap, Marker } from "react-google-maps"` in a pretty barebones project, I get the following error when trying to build using Webpack 2. It seems like `react-display-name` isn't installing its required deps:

**Stack Trace**
```
ERROR in ./~/react-display-name/lib/getDisplayName.js
Module build failed: Error: Couldn't find preset "es2015-loose" relative to directory "/Users/dvf/PycharmProjects/dig/node_modules/react-display-name"
    at /Users/dvf/PycharmProjects/dig/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/dvf/PycharmProjects/dig/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/dvf/PycharmProjects/dig/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/dvf/PycharmProjects/dig/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/dvf/PycharmProjects/dig/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/dvf/PycharmProjects/dig/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/dvf/PycharmProjects/dig/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/dvf/PycharmProjects/dig/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/dvf/PycharmProjects/dig/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (/Users/dvf/PycharmProjects/dig/node_modules/babel-loader/lib/index.js:171:20)
 @ ./~/react-google-maps/lib/withGoogleMap.js 45:24-53
 @ ./~/react-google-maps/lib/index.js
 @ ./assets/js/index.js
```

**webpack.config.json**
```
const path = require("path");
const webpack = require("webpack");
const BundleTracker = require("webpack-bundle-tracker");

module.exports = {
  entry: "./assets/js/index",
  output: {
    path: path.resolve(__dirname, "./assets/webpack_bundles/"),
    filename: "[name].bundle.js"
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        loader: "babel-loader",
        exclude: [path.resolve(__dirname, "./node-modules")],
        query: { presets: ["react"] }
      }
    ]
  },
  plugins: [new BundleTracker({ filename: "./webpack-stats.json" })]
};
```

**package.json**
```
{
  "name": "dig",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.25.0",
    "babel-loader": "^7.0.0",
    "babel-preset-env": "^1.5.2",
    "babel-preset-es2015-loose": "^8.0.0",
    "babel-preset-react": "^6.24.1",
    "html-webpack-plugin": "^2.28.0",
    "immutable": "^3.8.1",
    "prettier": "^1.4.4",
    "react-google-maps": "^6.3.0",
    "react-redux": "^5.0.5",
    "redux": "^3.6.0",
    "uglifyjs-webpack-plugin": "^0.4.3",
    "webpack": "^2.6.1",
    "webpack-bundle-tracker": "^0.2.0"
  },
  "dependencies": {
    "react": "^15.5.4",
    "react-dom": "^15.5.4"
  }
}
```

**Comment by tomchentw** [comment]
Please refer to [Getting Help](https://github.com/tomchentw/react-google-maps#getting-help) section in the README.
