### ISSUE TITLE
Module build failed: provided an invalid property of "__wrapped__"

### ISSUE THREAD

**Issue by subharb** [tomchentw/react-google-maps#739]
I've been following the instructions on how to get react-google-maps working and I always get this error after launching my webpack server:

> Module build failed: provided an invalid property of "__wrapped__"

If I shut the server and do a 
`npm install --save react-google-maps`

And start it again, it works OK, If I stop the server and start it again I get the same error. Anyone else gettin this error?

Thanks.

**Comment by tomchentw** [comment]
Please provide reproduce steps with a minimal working repository

**Comment by Ripza** [comment]
Hello. I have the same error. 

I just use yarn add react-google-maps and complete the Step 1 of the documentation.

I used parcel for app bundler. 

The error is: 

/node_modules/react-google-maps/lib/index.js: Plugin 0 specified in "/node_modules/react-google-maps/package.json" provided an invalid property of "__wrappe    at Plugin.init (/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at JSAsset.parse (/node_modules/parcel-bundler/src/assets/JSAsset.js:55:20)

**Comment by tomchentw** [comment]
Hmm it seems parcel is trying to load babel to compile `react-google-maps`? Not a good idea…

**Comment by subharb** [comment]
Here's my complete log:

> ERROR in ./~/react-google-maps/lib/index.js
Module build failed: Error: Plugin 0 specified in "/Users/david/Sites/jantoDocker/phalcon/public/node_modules/react-google-maps/package.json" provided an invalid property of "__wrapped__"
    at Plugin.init (/Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/Users/david/Sites/jantoDocker/phalcon/public/node_modules/babel-loader/lib/index.js:175:20)
 @ ./src/components/map_component.js 17:23-51
 @ ./src/containers/single_show.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.js

Here's my package.json:

> {
  "name": "janto5",
  "version": "1.0.0",
  "description": "Nueva versión de la web",
  "main": "index.js",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/StephenGrider/ReduxSimpleStarter.git"
  },
  "scripts": {
    "start": "webpack-dev-server --env.dev --open --watch --progress --colors",
    "postinstall": "webpack --env.prod -p"
  },
  "author": "David Shaikh Urbina",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/StephenGrider/ReduxSimpleStarter/issues"
  },
  "homepage": "https://github.com/StephenGrider/ReduxSimpleStarter#readme",
  "directories": {
    "test": "test"
  },
  "devDependencies": {
    "axios": "^0.16.2",
    "babel-cli": "^6.26.0",
    "babel-core": "^6.26.0",
    "babel-jest": "^21.2.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "bootstrap": "^3.3.7",
    "clean-webpack-plugin": "^0.1.17",
    "enzyme": "^3.1.0",
    "enzyme-adapter-react-16": "^1.0.2",
    "html-webpack-plugin": "^2.30.1",
    "jest": "^21.2.1",
    "react-addons-test-utils": "^15.6.2",
    "react-test-renderer": "^16.0.0",
    "uglifyjs-webpack-plugin": "^1.0.1",
    "webpack": "^2.7.0",
    "webpack-dev-server": "^2.9.2",
    "webpack-merge": "^4.1.1"
  },
  "dependencies": {
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-stage-0": "^6.24.1",
    "i": "^0.3.6",
    "jquery": "^3.2.1",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-facebook": "^4.1.1",
    "react-google-maps": "^9.4.3",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "react-sticky": "^6.0.1",
    "redux": "^3.7.2",
    "redux-form": "^7.1.1",
    "redux-promise": "^0.5.3",
    "redux-thunk": "^2.2.0",
    "styled-components": "^2.4.0"
  }
}

**Comment by tomchentw** [comment]
Please provide a minimal working repository

**Comment by subharb** [comment]
[Here you go](https://github.com/subharb/TestingReact-googlemaps)

**Comment by subharb** [comment]
Also I realised that I first have to uninstall react-google-maps component, then install it and restart webpack. Only executing the install command is not enough.

**Comment by tomchentw** [comment]
@subharb you need to add `exclude: /node_modules/` to your webpack config

```js
{
                use : {
                    loader: 'babel-loader',
                    query: {
                        presets: ['env', 'react', 'stage-1']
                    }
                },
                test : /\.js$/,
                exclude: /node_modules/
                
            }
```
Proof

<img width="1132" alt="screen shot 2018-01-05 at 8 59 38 pm" src="https://user-images.githubusercontent.com/922234/34610276-649366f6-f25b-11e7-9ae7-fdf4f4d10a4d.png">

**Comment by wzc5840** [comment]
I have the same error and 
package.json
{
  "name": "Ichigun",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "lodash": "^4.17.5",
    "react": "^16.3.0-alpha.1",
    "react-google-maps": "^9.4.5",
    "react-native": "0.54.3",
    "react-native-code-push": "^5.3.2",
    "react-native-fbsdk": "^0.7.0",
    "react-native-hud-view": "^1.2.2",
    "react-native-read-more-text": "^1.0.0",
    "react-native-splash-screen": "^3.0.6",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.5.8"
  },
  "devDependencies": {
    "babel-jest": "22.4.3",
    "babel-preset-react-native": "4.0.0",
    "jest": "22.4.3",
    "react-test-renderer": "^16.3.0-alpha.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
